### ISSUE TITLE
SQL Endpoint

### ISSUE THREAD

**Issue by host138** [elastic/elasticsearch-php#1091]
### Summary of problem or feature request

Can't run SQL query from php client. From Kibana it's works. 

### Code snippet of problem
```php
$client = Elasticsearch\ClientBuilder::create()
    ->setHosts($hosts)
    ->build();

$params = [
    'body' => [
        'query' => 'SELECT field FROM index LIMIT 10'
    ]
];

$response = $client->sql()->query($params);
var_dump($response);
```

I get the error: 

```Fatal error: Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":"Incorrect HTTP method for uri [/_sql] and method [POST], allowed: [GET, DELETE, HEAD, PUT]","status":405} in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:641 Stack trace: #0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(328): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array) #1 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #2 /var/www/html/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #3 /var/www/html/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #4 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(340): GuzzleHttp\Rin in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 641```

Please help, what is wrong there. 

PS. I can't find docs about sql queries in the php client.
Thank's in advance.

### System details
- Operating System - Centos 8.3
- PHP Version - 7.3
- ES-PHP client version 7.10
- Elasticsearch version 6.8.13

**Comment by host138** [comment]
I found a temporary solution for the problem: If you replace the URI from /_sql to /_xpack/sql, then it works correctly in the 
Elasticsearch\Endpoints\Sql\Query, in the return of getURI() method

```php

public function getURI(): string
{
   return "/_xpack/sql";
}
```

**Comment by feng99** [comment]
Will the insert and update functions work properly after the code is modified?

**Comment by ezimuel** [comment]
@host138 you used a mismatch version between Elasticsearch server `6.8.13` and `elasticsearch-php` `7.10`. If you are still using Elasticsearch 6 you need to use `elasticsearch-php` 6. I suggest to use the latest [v6.8.2](https://github.com/elastic/elasticsearch-php/releases/tag/v6.8.2).
