### ISSUE TITLE
index function why not support array?

### ISSUE THREAD

**Issue by feng99** [elastic/elasticsearch-php#1130]
### Code snippet of problem
![image](https://user-images.githubusercontent.com/13182572/115881427-50997180-a47e-11eb-8a3f-703a184763c1.png)
dsl  ,this is ok.

```
$params   = [
            'index' => 'test',
            'type'  => 'test',
            'id'    => '6',
            'body'  => ['int1' => [6, 7]]
        ];
        $client   = DiHelper::getEs();
        $response = $client->index($params);
        print_r($response);



```
err log
```

"code": "-101",
\nError Code: 400\n\n#0 /web/website/bobo.com/composer/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(295): Elasticsearch\\Connections\\Connection->process4xxError(Array, Array, Array)\n#1 /web/website/bobo.com/composer/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array)\n#2 

/web/website/bobo.com/composer/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n#3 /web/website//bobo.com/composer/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\n#4 

/web/website/bobo.com/composer/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(315): GuzzleHttp\\Ring\\Core::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\n#5 /web/website/bobo.com/composer/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(187): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array, Object(Elasticsearch\\Connections\\Connection), Object(Elasticsearch\\Transport), Array)\n#6 /web/website/bobo.com/composer/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(107): Elasticsearch\\Connections\\Connection->performRequest('PUT', '/test/test/7/_c...', Array, '{\"int1\":[4,5]}', Array, Object(Elasticsearch\\Transport))\n#7 


/web/website/bobo.com/composer/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1586): Elasticsearch\\Transport->performRequest('PUT', '/test/test/7/_c...', Array, Array, Array)\n#8 /web/website//bobo.com/composer/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(760): Elasticsearch\\Client->performRequest(Object(Elasticsearch\\Endpoints\\Create))\n#9 

/web/website/bobo.com/app/backend/Controllers/TestController.php(231): Elasticsearch\\Client->create(Array)\n#10 [internal function]: TestController->esV1Action('App\\\\Backend\\\\Con...', 'test', 'es', 'v1', 'test/es/v1', '/v1/test/es')\n#11 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(TestController), 'esV1Action', Array)\n#12 [internal function]: Phalcon\\Dispatcher->dispatch()\n#13 /web/website/bobo.com/app/Sdks/Core/System/Application/CustomApplication.php(28): Phalcon\\Mvc\\Application->handle()\n#14 /web/website/bobo.com/app/bootstrap/bootstrap.php(142): 

App\\Sdks\\Core\\System\\Application\\CustomApplication->run()\n#15 /web/website/bobo.com/public/index.php(4): require('/web/website/co...')\n#16 {main}\narray (\n  'Hm_lvt_43f07e50f9738318fa872f35b04004c9' => '1612249465,1612768050',\n  '_url' => '/v1/test/es',\n)\n",


```

### System details

- Operating System
- PHP Version
- 7.3
- ES-PHP client version
- 6.*
- Elasticsearch version
-6.8

**Comment by ezimuel** [comment]
@feng99 sorry for the late reply. The code that you pasted seems correct, are you sure that `$client` is a valid instance of `Elasticsearch\Client`? I tried the following code with `Elasticsearch 6.8.0` and `elasticsearch-php 6.8.0` and everything works fine:
```php
use Elasticsearch\ClientBuilder;

require 'vendor/autoload.php';

$client = ClientBuilder::create()->build();

$params   = [
    'index' => 'test',
    'type'  => 'test',
    'id'    => '6',
    'body'  => ['int1' => [6, 7]]
];
$response = $client->index($params);
print_r($response);
```

The output is:
```
Array
(
    [_index] => test
    [_type] => test
    [_id] => 6
    [_version] => 1
    [result] => created
    [_shards] => Array
        (
            [total] => 2
            [successful] => 1
            [failed] => 0
        )

    [_seq_no] => 0
    [_primary_term] => 1
)
~/
```

**Comment by feng99** [comment]
![image](https://user-images.githubusercontent.com/13182572/119788406-b1e0b480-bf04-11eb-9c55-b9fa22797eee.png)

**Comment by feng99** [comment]
All other functions work, but this batch operation does not work
