### ISSUE TITLE
Serialization  error in Laravel "Serialization of 'Closure' is not allowed"

### ISSUE THREAD

**Issue by nicolasvahidzein** [elastic/elasticsearch-php#1188]
Hello

I am having an error in Laravel where i get this error:

```
[2021-12-22 20:21:17] local.ERROR: Serialization of 'Closure' is not allowed {"userId":1,"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at D:\WebServer\ZeinTekWebServices\liveroot\merlin-core\vendor\laravel\framework\src\Illuminate\Queue\Queue.php:139)
```

Here is my Searchable class:
```
<?php

namespace App\Search;

//Issues
//AUDIT_00001-PENDING

trait Searchable {
	
    public static function bootSearchable() {
		
        // This makes it easy to toggle the search feature flag
        // on and off. This is going to prove useful later on
        // when deploy the new search engine to a live app.
        if (config('services.search.enabled')) {
            static::observe(ElasticsearchObserver::class);
		}
		
	}
	
    public function getSearchIndex() {
        return $this->getTable();
	}
	
    public function getSearchType() {
		
		if (property_exists($this, 'useSearchType')) {
            return $this->useSearchType;
		}
		
		return $this->getTable();
		
	}
	
    public function toSearchArray() {
		
        // By having a custom method that transforms the model
        // to a searchable array allows us to customize the
        // data that's going to be searchable per model.
		return $this->toArray();
		
	}
	
}
```

This is the Oberserver called in the trait:
```
<?php

namespace App\Search;

use App\Jobs\Search\ElasticSearchSaveData;
use App\Jobs\Search\ElasticSearchDeleteData;

//Issues
//AUDIT_00001-PENDING

class ElasticsearchObserver {
	
    public function __construct() {
        //
	}
	
    public function saved($model) {
		
        ElasticSearchSaveData::dispatch($model)->delay(now()->addSeconds(2)); 
		
	}
	
    public function deleted($model) {
		
		ElasticSearchDeleteData::dispatch($model)->delay(now()->addSeconds(2));
		
	}
	
}
```

And here is the class called on saved:
```
<?php

namespace App\Jobs\Search;

//system classes
use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Elasticsearch\ClientBuilder;
use Log;

//models

//Custom methods

//Issues
//AUDIT_00001-PENDING

class ElasticSearchSaveData implements ShouldQueue {
	
	private $className = 'App\Jobs\Search\ElasticSearchSaveData.php';
	private $elasticsearch; // @var \Elasticsearch\Client
	private $model;
	
	use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
	
	public function __construct($model) {
		
		$this->elasticsearch = ClientBuilder::create()->build();
		$this->model = $model;
		
	}
	
	public function handle() {
		if (config('settings.DebugTraceLevelFunctions') == true) { Log::info('handle function in '.$this->className); }//this is a special log function for queue job classes
		
		//retrieve all the variables we need
		$model = $this->model;
		
		$this->elasticsearch->index([
            'index' => $model->getSearchIndex(),
            'type' => $model->getSearchType(),
            'id' => $model->getKey(),
            'body' => $model->toSearchArray(),
		]);
		
		//done saving model data
		
	}
	
}
```

Here is the full error stack:
```
[2021-12-22 20:21:17] local.ERROR: Serialization of 'Closure' is not allowed {"userId":1,"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Queue.php:139)
[stacktrace]
#0 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Queue.php(139): serialize(Object(App\\Jobs\\Search\\ElasticSearchSaveData))
#1 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Queue.php(110): Illuminate\\Queue\\Queue->createObjectPayload(Object(App\\Jobs\\Search\\ElasticSearchSaveData), 'default')
#2 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Queue.php(88): Illuminate\\Queue\\Queue->createPayloadArray(Object(App\\Jobs\\Search\\ElasticSearchSaveData), 'default', '')
#3 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\DatabaseQueue.php(111): Illuminate\\Queue\\Queue->createPayload(Object(App\\Jobs\\Search\\ElasticSearchSaveData), 'default', '')
#4 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(181): Illuminate\\Queue\\DatabaseQueue->later(Object(Illuminate\\Support\\Carbon), Object(App\\Jobs\\Search\\ElasticSearchSaveData))
#5 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(160): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\DatabaseQueue), Object(App\\Jobs\\Search\\ElasticSearchSaveData))
#6 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\Search\\ElasticSearchSaveData))
#7 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bus\\PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\Search\\ElasticSearchSaveData))
#8 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\app\\Search\\ElasticsearchObserver.php(19): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#9 [internal function]: App\\Search\\ElasticsearchObserver->saved(Object(App\\Models\\ProductsListing))
#10 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(366): call_user_func_array(Array, Array)
#11 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(196): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.saved:...', Array)
#12 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasEvents.php(188): Illuminate\\Events\\Dispatcher->dispatch('eloquent.saved:...', Array)
#13 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(708): Illuminate\\Database\\Eloquent\\Model->fireModelEvent('saved', false)
#14 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(679): Illuminate\\Database\\Eloquent\\Model->finishSave(Array)
#15 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(795): Illuminate\\Database\\Eloquent\\Model->save()
#16 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(1124): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(App\\Models\\ProductsListing))
#17 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(796): tap(Object(App\\Models\\ProductsListing), Object(Closure))
#18 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create(Array)
#19 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1618): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'create', Array)
#20 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1630): Illuminate\\Database\\Eloquent\\Model->__call('create', Array)
#21 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\app\\Methods\\Products\\CreateProductListing.php(152): Illuminate\\Database\\Eloquent\\Model::__callStatic('create', Array)
#22 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\app\\Methods\\Products\\AddProduct.php(66): App\\Methods\\Products\\CreateProductListing->create(Object(App\\User), '{\"uid\":\"c78d058...')
#23 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\app\\Http\\Controllers\\API\\ProductsController.php(145): App\\Methods\\Products\\AddProduct->add(Object(App\\User), '{\"uid\":\"c78d058...')
#24 [internal function]: App\\Http\\Controllers\\API\\ProductsController->addProduct(Object(Illuminate\\Http\\Request))
#25 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#26 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('addProduct', Array)
#27 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\API\\ProductsController), 'addProduct')
#28 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#29 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(680): Illuminate\\Routing\\Route->run()
#30 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\app\\Http\\Middleware\\CheckAccessCustom.php(273): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\CheckAccessCustom->handle(Object(Illuminate\\Http\\Request), Object(Closure), false, false, false, false, false, true)
#33 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\app\\Http\\Middleware\\CheckSectionMobileAdmin.php(61): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): App\\Http\\Middleware\\CheckSectionMobileAdmin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#42 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#45 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#49 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#50 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#51 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#52 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#53 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\barryvdh\\laravel-cors\\src\\HandleCors.php(36): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#73 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#74 D:\\WebServer\\ZeinTekWebServices\\liveroot\\merlin-core\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#75 {main}
"} 
```

**Comment by ezimuel** [comment]
The message error `Serialization of 'Closure' is not allowed` is generated because somewhere in your code you are serializing an anonymous function. I found many reference of this error in stackoverflow for Laravel (e.g. [here](https://stackoverflow.com/questions/46004840/exception-serialization-of-closure-is-not-allowed-in-queue-php-line-127)).
I didn't found any evidence of a class related to `elasticsearch-php` in the stack trace that you reported. I think this is an issue of Laravel and you should investigate in the Laravel community about this.
I'm closing this issue but if you find any evidence that the error can be related to `elasticsearch-php` let me know and I'll reopen it. Thanks.
