### ISSUE TITLE
IndexMissingException[[*] missing

### ISSUE THREAD

**Issue by itonics-tbeauvais** [elastic/elasticsearch-php#188]
This command works locally but doesn't when I push to Heroku.

What can cause this problem?  If there are no indices, it should just return none right?

```
   exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
   [status code] 404
   [reason phrase] Not Found
   [url] https://birch-9353409.eu-west-1.bonsai.io/_mapping' in /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
   Stack trace:
   #0 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Message\Response))
   #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
   #2 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
   #3 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
   #4 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
   #5 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
   #6 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\Request->setState('complete', Array)
   #7 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
   #8 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
   #9 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
   #10 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
   #11 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
   #12 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
   #13 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\Request))
   #14 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
   #15 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\Request), NULL)
   #16 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/_mapping', Array, NULL)
   #17 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/_mapping', Array, NULL)
   #18 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(335): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
   #19 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/app/Console/Commands/Clear.php(68): Elasticsearch\Namespaces\IndicesNamespace->getMapping()
   #20 [internal function]: Lebowski\Console\Commands\Clear->fire()
   #21 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
   #22 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
   #23 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #24 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #25 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #26 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Lebowski\Console\Commands\Clear), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #27 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #28 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #29 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #30 {main}

   Next exception 'Elasticsearch\Common\Exceptions\Missing404Exception' with message '{"error":"IndexMissingException[[*] missing]","status":404}' in /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php:260
   Stack trace:
   #0 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Exception\ClientErrorResponseException), NULL)
   #1 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\Request), NULL)
   #2 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/_mapping', Array, NULL)
   #3 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/_mapping', Array, NULL)
   #4 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(335): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
   #5 /tmp/build_7ebad77f02a0e4bfd3d63ff4aea98a1b/app/Console/Commands/Clear.php(68): Elasticsearch\Namespaces\IndicesNamespace->getMapping()
```

**Comment by polyfractal** [comment]
What version of Elasticsearch is running on your Heroku instance?  Older versions of ES throw exceptions like this sometimes (e.g. [here is a similar issue](https://github.com/elasticsearch/elasticsearch/issues/3534) that was fixed in 1.0).

On my local machine I'm running 1.3.4 and get what you would expect:

```
$ curl -XGET "http://localhost:9200/_mapping"

{}
```

**Comment by itonics-tbeauvais** [comment]
version: {
number: "1.3.6",
build_hash: "b5a430a8ef84cc5135edc880d8b0770b50b20441",
build_timestamp: "2015-01-29T19:20:05Z",
build_snapshot: false,
lucene_version: "4.9"
}

**Comment by polyfractal** [comment]
Sorry, this got lost in the ticket list.  Did this ever get resolved on your end?

**Comment by ngocdb** [comment]
I have the same issue with the version 1.2.4
If there is no index (for example index id non exists), an exception is thrown instead of none.
#0 /media/datas/websites/marketplace/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Exception\ClientErrorResponseException), NULL)
#1 /media/datas/websites/marketplace/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\Request), NULL)
#2 /media/datas/websites/marketplace/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/thesaurus/thes...', Array, NULL)
#3 /media/datas/websites/marketplace/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/thesaurus/thes...', Array, NULL)
#4 /media/datas/websites/marketplace/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(177): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
...

Version:
{
  "status" : 200,
  "name" : "Adaptoid",
  "version" : {
    "number" : "1.2.4",
    "build_hash" : "11689ab5f166203d21f1a3c566fe8e96b1d4cd75",
    "build_timestamp" : "2014-08-13T14:09:19Z",
    "build_snapshot" : false,
    "lucene_version" : "4.8"
  },
  "tagline" : "You Know, for Search"
}

**Comment by polyfractal** [comment]
Closing due to age, this is likely not relevant with 2.x and 5.x anymore.
