### ISSUE TITLE
Uncaught exception from Guzzle when searching not existing index

### ISSUE THREAD

**Issue by ein-wuppertaler** [elastic/elasticsearch-php#230]
Hi there,
with PHP 5.4.39 and Elasticsearch 1.5.1 (not sure about elasticsearch-php version, should be 1.3.4 as I'm not getting updates from composer) I'm doing 
```php
<?php
require 'vendor/autoload.php';

$client = new Elasticsearch\Client();
$params = array();
$params['index'] = 'absent_index';
$params['body']='{  "query" : { "match_all" : {} },  "sort" : [ { "absent_field" : "desc" } ],  "size" : 2000 }';
$results = $client->search($params);
?>
```

and I get 
```
<br />
<b>Fatal error</b>:  Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 404
[reason phrase] Not Found
[url] http://localhost:9200/absent_index/_search' in /usr/share/nginx/www/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /usr/share/nginx/www/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /usr/share/nginx/www/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /usr/share/nginx/www/vendor/symfony/event-dispatcher/Symfony/C in <b>/usr/share/nginx/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php</b> on line <b>265</b><br />
```
Is it me? :flushed:

Cheers,
Markus

**Comment by polyfractal** [comment]
What's the output for:  `curl -XGET http://localhost:9200/absent_index/_search` ?

The 404 basically means that the `absent_index` index isn't in your cluster.  Elasticsearch returns a 404 missing, which the client translates into a thrown exception.  If you know the index is missing and want to deal with that potential failure mode, you can catch them:

```php
$params = array();
$params['index'] = 'absent_index';
$params['body']='{  "query" : { "match_all" : {} },  "sort" : [ { "absent_field" : "desc" } ],  "size" : 2000 }';

try {
  $results = $client->search($params);
} catch (Missing404Exception $e) {
  print_r($e->getMessage());
}
```

Or you can tel the client to ignore certain exceptions:

```php
$params = array();
$params['index'] = 'absent_index';
$params['body']='{  "query" : { "match_all" : {} },  "sort" : [ { "absent_field" : "desc" } ],  "size" : 2000 }';

//Ignore 404 exceptions
$params['ignore'] = 404
$results = $client->search($params);
```

**Comment by ein-wuppertaler** [comment]
Hi Zachary,
I'll use your your code to avoid crashing the php script, thanks! :-)

If needed ...
```
# curl -XGET http://localhost:9200/absent_index/_search
{"error":"IndexMissingException[[absent_index] missing]","status":404}
```

Thanks again,
Markus

**Comment by polyfractal** [comment]
Ah ok, the index was actually missing.  I was concerned it was present but throwing a missing exception :)

As an aside, the client converts *all* errors from Elasticsearch into equivalent exceptions (e.g. 404, 409, 500, etc).  So you can apply the catch or ignore pattern to most APIs in the client.
