### ISSUE TITLE
cURL error 7

### ISSUE THREAD

**Issue by jeremyhodges** [elastic/elasticsearch-php#329]
Trying to connect to ES hosted with ObjectRocket, but get the following error...

```
Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\TransportException' with message 'cURL error 7: See http://curl.haxx.se/libcurl/c/libcurl-errors.html'
in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:201 Stack trace:
#0 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#1 /var/www/html/vendor/react/promise/src/Promise.php(114): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#2 /var/www/html/vendor/react/promise/src/Promise.php(159): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#3 /var/www/html/vendor/react/promise/src/Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#4 /var/www/html/vendor/react/promise/src/Promise.php(177): React\Promise\Promise->resolve(Array)
#5 [internal function]: React\Promise\Promise->React\Promise\{closure}(Array)
#6 /var/www/html/vendor/react/pro in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 201
```

```php
<?php
  
  ini_set('display_errors', 1);
  ini_set('display_startup_errors', 1);
  error_reporting(E_ALL);
  
  require 'vendor/autoload.php';
  
  use Elasticsearch;
  use Elasticsearch\ClientBuilder;
  
  $multiHandler = ClientBuilder::multiHandler();
  
  $hosts = [
    'http://user:pass@0.es.objectrocket.com:10183',
    'http://user:pass@1.es.objectrocket.com:10183',
    'http://user:pass@2.es.objectrocket.com:10183',
    'http://user:pass@3.es.objectrocket.com:10183'
  ];
  
  $client = ClientBuilder::create()->setHosts($hosts)->setHandler($multiHandler)->build();
  
  $params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
    'body' => [
      'testField' => 'abc'
    ]
  ];
  
  $response = $client->index($params);
  print_r($response);
?>
```

But if I run the `curl` command from the terminal it I have no problem connecting...

```
curl -XGET http://user:pass@0.es.objectrocket.com:10183
```

**Comment by polyfractal** [comment]
Hm, I'm not sure.  Could you try the verbose mode and paste the output (scrubbing any confidential info first):

```php
  $params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
    'body' => [
      'testField' => 'abc'
    ],
    'client' => [
        'verbose' => true
    ]
  ];
```

Some other things to try:

- Could you try removing the `setHandler()` line, to rule out the custom-handler code as a source of bugs
- Could you try only setting one host (`http://user:pass@0.es.objectrocket.com:10183`) to rule out round-robin as the source?

What version of ES-PHP 2.0 are you on?  There was a small change to HTTP auth in 2.0.2 (https://github.com/elastic/elasticsearch-php/commit/4b01af8) and I'm wondering if that was the cause.

**Comment by jeremyhodges** [comment]
Looks like I am running 2.0.2, but I tried rolling back those changes you highlighted and still got the same error. I get the same exact error trying to use verbose mode.

```php
<?php
  
  ini_set('display_errors', 1);
  ini_set('display_startup_errors', 1);
  error_reporting(E_ALL);
  
  require 'vendor/autoload.php';
    
  use Elasticsearch;
  use Elasticsearch\ClientBuilder;
  
  $hosts = [
    'http://user:pass@0.es.objectrocket.com:10183'
  ];
  
  $client = ClientBuilder::create()->setHosts($hosts)->build();
  
  $params = [
    'index' => 'my_index',
    'type' => 'my_type',
    'id' => 'my_id',
    'body' => [
      'testField' => 'abc'
    ],
    'client' => [
        'verbose' => true
    ]
  ];
  
  $response = $client->index($params);
  print_r($response);

?>
```

**Comment by polyfractal** [comment]
Oh, doh, sorry...the exception is messing it up.  If you can upgrade to v2.0.3, you can try this instead:

```php
try {
  $response = $client->index($params);
} catch (Exception $e) {
  print_r($client->transport->getLastConnection()->getLastRequestInfo());
}
```

**Comment by jeremyhodges** [comment]
Just a simple 3,600 line text file... https://drive.google.com/file/d/0BzV1MrqDAMeud244T0pPRTFnNEE/view?usp=sharing

**Comment by polyfractal** [comment]
Argh, yeah, print_r freaks out about recursive/cyclic data structures (like the promises in Ring).  Thanks for the dump though, it helps a bit...wanted to rule out some kind of redirection problem.

Honestly...I have no idea.  I'm going to sign up for an ObjectRocket trial and see if I can debug further.

What version of curl is PHP using?  Is it the same as your cli?  Very rarely there will be a libcurl bug on a particular platform, but I'm not hopeful this is one of those cases ;)

```php
print_r(curl_version());
```
```
$ curl --version
```

**Comment by jeremyhodges** [comment]
```

Array
(
    [version_number] => 466176
    [age] => 3
    [features] => 34493
    [ssl_version_number] => 0
    [version] => 7.29.0
    [host] => x86_64-redhat-linux-gnu
    [ssl_version] => NSS/3.15.4
    [libz_version] => 1.2.7
    [protocols] => Array
        (
            [0] => dict
            [1] => file
            [2] => ftp
            [3] => ftps
            [4] => gopher
            [5] => http
            [6] => https
            [7] => imap
            [8] => imaps
            [9] => ldap
            [10] => ldaps
            [11] => pop3
            [12] => pop3s
            [13] => rtsp
            [14] => scp
            [15] => sftp
            [16] => smtp
            [17] => smtps
            [18] => telnet
            [19] => tftp
        )

)
```

```
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.15.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz 
```

**Comment by jeremyhodges** [comment]
Just as some more troubleshooting, I ran this curl from the command line and it worked just fine...

```
[root@localhost /]# curl -XPUT "http://user:pass@0.es.objectrocket.com:10183/movies/movie/1" -d'
{
    "title": "The Godfather",
    "director": "Francis Ford Coppola",
    "year": 1972
}'
{"_index":"movies","_type":"movie","_id":"1","_version":1,"created":true}[root@localhost /]# 
```

Then ran this and get the same exception as before...

```php
$hosts = [
    'http://user:pass@0.es.objectrocket.com:10183'
  ];
  
  $client = ClientBuilder::create()->setHosts($hosts)->build();
  
  $params = [
    'index' => 'movie',
    'type' => 'movies',
    'id' => '3',
    'body' => [
      'title' => 'The Godfather',
      'director' => 'Francis Ford Coppola',
      'year' => 1972
    ],
    'client' => [
        'verbose' => true
    ]
  ];
  
  try {
    $response = $client->index($params);
    print_r($response);
  } catch (Exception $e) {
    print_r($client->transport->getLastConnection()->getLastRequestInfo());
  }
```

**Comment by polyfractal** [comment]
Have you configured the ObjectRocket ACL for the machine that is sending the request?  I was getting the same curl 7 error until I configured the ACL, now everything seems to be working:

```php

$hosts = [
    'http://user:pass@iad1-10191-0.es.objectrocket.com:10191'
];

$client = ClientBuilder::create()->setHosts($hosts)->build();

$params = [
    'index' => 'movie',
    'type' => 'movies',
    'id' => '3',
    'body' => [
        'title' => 'The Godfather',
        'director' => 'Francis Ford Coppola',
        'year' => 1972
    ],
    'client' => [
        'verbose' => true
    ]
];

print_r($client->index($params));
```
```
Array
(
    [transfer_stats] => Array
        (
            [url] => http://iad1-10191-0.es.objectrocket.com:10191/movie/movies/3
            [content_type] => application/json; charset=UTF-8
            [http_code] => 200
            [header_size] => 172
            [request_size] => 208
            [filetime] => -1
            [ssl_verify_result] => 0
            [redirect_count] => 0
            [total_time] => 0.200325
            [namelookup_time] => 0.00485
            [connect_time] => 0.074404
            [pretransfer_time] => 0.074493
            [size_upload] => 71
            [size_download] => 74
            [speed_download] => 369
            [speed_upload] => 354
            [download_content_length] => 74
            [upload_content_length] => 71
            [starttransfer_time] => 0.200208
            [redirect_time] => 0
            [redirect_url] => 
            [primary_ip] => 69.20.6.80
            [certinfo] => Array
                (
                )
            [primary_port] => 10191
            [local_ip] => 192.168.0.3
            [local_port] => 52569
            [error] => 
            [errno] => 0
        )
    [curl] => Array
        (
            [error] => 
            [errno] => 0
        )
    [effective_url] => http://iad1-10191-0.es.objectrocket.com:10191/movie/movies/3
    [headers] => Array
        (
            [Server] => Array
                (
                    [0] => Banana4Webscale
                )
            [Date] => Array
                (
                    [0] => Tue, 24 Nov 2015 21:24:39 GMT
                )
            [Content-Type] => Array
                (
                    [0] => application/json; charset=UTF-8
                )
            [Content-Length] => Array
                (
                    [0] => 74
                )
            [Connection] => Array
                (
                    [0] => keep-alive
                )
        )
    [version] => 1.1
    [status] => 200
    [reason] => OK
    [body] => Array
        (
            [_index] => movie
            [_type] => movies
            [_id] => 3
            [_version] => 2
            [created] => 
        )
)
```

**Comment by jeremyhodges** [comment]
Yes, I have the ACL set to allow any IP to access ElasticSearch.

**Comment by polyfractal** [comment]
I'm thinking there must be something odd about this particular setup, since it seems to work with my instance of ObjectRocket.  Firewalls?  IP tables?  Insufficient user access rights for the PHP script?  

I see you're on redhat, you should also check SELinux and make sure the non-standard ports are allowed, etc.  IIRC the default is to disallow any curl wrapper that hits a non-standard port...you have to explicitly open those when SELinux is in "enforcing" mode.

Also might try setting the ACL explicitly to machine with the client.

**Comment by jeremyhodges** [comment]
You nailed it! Sure enough, it's because of the SELinux configuration. Much appreciated @polyfractal

**Comment by polyfractal** [comment]
Hooray!  \o/

And pheww...i was starting to scrape the bottom of the barrel of ideas :)  Happy that we got it sorted out, goodluck!
