### ISSUE TITLE
Elasticsearch-PHP 'Guzzle\Http\Exception\ClientErrorResponseException'

### ISSUE THREAD

**Issue by hilalgur** [elastic/elasticsearch-php#396]
Hi,
I have mysql data field 'islem'. It has some values. It's default value is 'Y'. For example;
islem=Y
islem=YD
islem=YDI
islem=YDDD
islem=YI
islem=YDS
islem=YS
islem=YDDDD.. etc

I did nested mapping this field on sense editor. Because this field has to be array. 
```
DELETE _all
PUT ihaleler
PUT ihaleler/ihale/_mapping
{
  "properties": {
    "islem": {
      "type": "nested"
    }  }}
```
After I indexed with PHP codes.(`http://10.0.2.15:8080/index.php?p=index`) But It has error:
```
Fatal error:  Uncaught exception 
'Guzzle\Http\Exception\ClientErrorResponseException' with message 
'Client error response
[status code] 400
[reason phrase] Bad Request
[url] http://localhost:9200/ihaleler/ihale/1030235' in 
/home/admin/web/server.com/public_html/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack
 trace:
#0 
/home/admin/web/server.com/public_html/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145):
 
Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest),
 Object(Guzzle\Http\Message\Response))
#1 [internal function]: 
Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event),
 'request.error', 
Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 
/home/admin/web/server.com/public_html/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164):
 call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', 
Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /home/admin/web/ in /home/admin/web/server.com/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php on line 266
```
My php codes:(index.php):

```
if($page=='index'){
	$db->orderBy('id','desc');
	$ihaleler=$db->get('tbl_ihale');
	foreach($ihaleler as $ihale){
		$id=$ihale['id'];
		if($id>0){
			$params=array();

                        $islem=$ihale['islem'];
			$islem=trim($islem, ',');
			$islem_array=explode(',', $islem);
			$islem_array=array_unique($islem_array);
			
			$dizi=array();
			$dizi['id']=$id*1;
			$dizi['islem']=$ihale['islem'];
			$dizi['adi']=$ihale['adi'];
	
 			$params['body']=$dizi;
			$params['index']=$index_name;
			$params['type']=$type_name;
			$params['id']=$id;
}			$ret=$client->index($params);
		}}}?>   
```
Can you please help me?
Thank you..

**Comment by polyfractal** [comment]
Can you paste a `print_r($params)` so we can see what the final object looks like?

I see that you are constructing `$islem_array`, but it is never used anywhere...perhaps that's the problem?  E.g. your mapping says `"islem"` is an array of nested objects, but your code sets it to `$ihale['islem']` instead of `$islem_array`.  Could that be the problem?

**Comment by hilalgur** [comment]
I changed `$ihale['islem']: `

`$dizi['islem']=$islem_array;
`
I did print_r($params): 
result: 
```
Array ( [body] => Array ( [id] => 1030235 [islem] => Array ( [0] => Y ) ) [index] => ihaleler [type] => ihale [id] => 1030235 )
Fatal error: Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 400 [reason phrase] Bad Request [url] http://localhost:9200/ihaleler/ihale/1030235' in /home/admin/web/server.com/public_html/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43 Stack trace: #0 /home/admin/web/server.com/public_html/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response)) #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/admin/web/server.com/public_html/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 /home/admin/web/ in /home/admin/web/server.com/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php on line 266
```

**Comment by polyfractal** [comment]
Ok, so I think the problem was how the body is specified.  But let's back up.

If you just want an array for a field, you don't need nested mappings.  All fields can automatically turn into multi-valued arrays.  No need for special `nested` mapping.  Try this:

```
DELETE ihaleler
PUT ihaleler
PUT ihaleler/ihale/_mapping
{
  "properties": {
    "islem": {
      "type": "string"
    }  
  }
}
```

And then run your code.  I think that should work.

Also a potential problem, I see that ` $ret=$client->index($params);` is outside of the conditional `if($id>0) { ... }`.  Which means if the `$id` is equal to zero, it will try to send an indexing request with no parameters.  You may want to move that inside the conditional.

**Comment by hilalgur** [comment]
Thank you. I changed some codes.
### 1. My mapping:
```
DELETE _all
PUT ihaleler
PUT ihaleler/ihale/_mapping
{  "properties": {
    "islem": {
      "type": "string",
      "index": "analyzed",
      "analyzer": "turkish"
    } }}
```
2. index.php:
```
if($page=='index'){
	$db->orderBy('id','desc');
	$ihaleler=$db->get('tbl_ihale');
	foreach($ihaleler as $ihale){
		$id=$ihale['id'];
		if($id>0){
			$params=array();
                        $islem=$ihale['islem'];
			$islem=trim($islem, ',');
			$islem_array=explode(',', $islem);
			$islem_array=array_unique($islem_array);
        $dizi=array();
        $dizi['islem']=$islem_array;
        $params['body']=$dizi;
	$params['index']=$index_name;
	$params['type']=$type_name;
        $params['id']=$id;
        $ret=$client->index($params);
	}}exit('added');
} ?>   
```
3. filter.php
```
unset($filter_islem);
if(isset($_GET['islem'])){
    	$filter_islem['match_phrase']['islem']=$_GET['islem'];
}
if(is_array($filter_islem)){
	$searchParams['body']['query']['bool']['should']=$filter_islem;
}
$searchParams['body']['sort']['id']['order'] = 'asc';
pa($searchParams);
br();br();br();
echo $sorgus = mc();br();
$queryResponse = $client->search($searchParams);
$kayitlar = $queryResponse['hits'];
echo $total = $kayitlar['total'];
$kayitlar = $kayitlar['hits'];
foreach($kayitlar as $kayit){
      $_source = $kayit['_source'];
      pa($_source['islem']);
}
exit('the end');
?>
```
My query : `http://10.0.2.15:8080/filter.php?islem=YDDDDD`
Result is true:
```
Array
(
    [0] => YDDDDD
)
Array
(
    [0] => YDDDDD
)
```
However, I have a question : 
YDDDDD=YD
YDDDD=YD
YDD=YD
YD=YD  

or
YDDDI=YDI
YDDDS=YDS
YDSI=YDSI
YDDDSI=YDSI..

My result shoulnd't be islem=YDDDDDD .
It should be islem=YD. Five of the D here is unnecessary.
I want to unigue_array(). How can I do?

**Comment by polyfractal** [comment]
This seems to be a more general question about PHP and Elasticsearch, rather than just the PHP client itself.  I think you should post your question at the Elasticsearch discussion forums:  https://discuss.elastic.co/c/elasticsearch

There are more eyes there, and tickets here should really be about issues with the client itself.

**Comment by hilalgur** [comment]
I did but there are same answer. I did string mapping. So It was true.
Thank you. 
Have a good day
