### ISSUE TITLE
Validation Failed: 1: scrollId is missing;

### ISSUE THREAD

**Issue by 1e1** [elastic/elasticsearch-php#405]
I've just updated from v2.1.4 to v2.1.5. 

With the same code I have now: 

```
<br />
<b>Fatal error</b>:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {&quot;error&quot;:{&quot;root_cause&quot;:[{&quot;type&quot;:&quot;action_request_validation_exception&quot;,&quot;reason&quot;:&quot;Validation Failed: 1: scrollId is missing;&quot;}],&quot;type&quot;:&quot;action_request_validation_exception&quot;,&quot;reason&quot;:&quot;Validation Failed: 1: scrollId is missing;&quot;},&quot;status&quot;:400} in /home/scm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:655
Stack trace:
#0 /home/scm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(632): Elasticsearch\Connections\Connection-&gt;tryDeserializeError(Array, 'Elasticsearch\\C...')
#1 /home/scm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(553): Elasticsearch\Connections\Connection-&gt;tryDeserialize400Error(Array)
#2 /home/scm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(262): Elasticsearch\Connections\Connection-&gt;process4xxError(Array, Array, Array)
#3 /home/scm/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Con in <b>/home/scm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php</b> on line <b>657</b><br />
```

```
        $parameters = [
            'index' => 'my-alias',
            'type' => 'myType',
            'size' => $this->config['bulk_maxsize'],
            'scroll' => '5s',
            'search_type' => 'scan',
            'body' => [],
        ];

        $output = [];
        $fields = self::getFields();
        $infos = $this->elastic->search($parameters);
        $left = $infos['hits']['total'];

        if (!isset($infos['_scroll_id'])) {
            return;
        }

        $parameters = [
            'scroll_id' => $infos['_scroll_id'],
            'body' => '',
        ];

        while ($left > 0) {
            $infos = $this->elastic->scroll($parameters);
            foreach ($infos['hits']['hits'] as &$document) {
                $src = $document['_source'];
                $item = [];

                foreach ($fields as $field) {
                    if (isset($src[$field])) {
                        $item[$field] = $src[$field];
                    }
                }

                $output[$document['_id']] = $item;
                --$left;
            }
        }

        return $output;
```
- Operating System: Docker version 1.10.3, build 20f81dd
- PHP Version: 7.0.4
- ES-PHP client version: 2.1.5
- Elasticsearch version: 2.2.0

**Comment by ezimuel** [comment]
Outdated issue. No still relevant in 7.0.0.
