### ISSUE TITLE
Host error

### ISSUE THREAD

**Issue by satsam** [elastic/elasticsearch-php#479]
I Installed elasticsearch in separate server and nginx as web server

I have add elasticsearch-php library using composer in another server

When i call elaslticsearch using command line curl -k https://remotehost:80/ its working

In php its not working 

```
**Error Log**

[Mon Oct 17 19:45:29.531815 2016] [cgi:error] [pid 25245] [client 163.158.164.227:28451] AH01215: PHP Fatal error:  Uncaught exception 'Elasticsearch\\Common\\Exceptions\\InvalidArgumentException' with message 'Hosts parameter must be an array of strings' in /home2/user/public_html/elastic/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php:521: /usr/local/cpanel/cgi-sys/ea-php56
[Mon Oct 17 19:45:29.531984 2016] [cgi:error] [pid 25245] [client 163.158.164.227:28451] AH01215: #0 /home2/user/public_html/elastic/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php(468): Elasticsearch\\ClientBuilder->buildConnectionsFromHosts('141.185.173.164'): /usr/local/cpanel/cgi-sys/ea-php56
[Mon Oct 17 19:45:29.532062 2016] [cgi:error] [pid 25245] [client 163.158.164.227:28451] AH01215: #1 /home2/user/public_html/elastic/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php(426): Elasticsearch\\ClientBuilder->buildTransport(): /usr/local/cpanel/cgi-sys/ea-php56
[Mon Oct 17 19:45:29.532107 2016] [cgi:error] [pid 25245] [client 162.158.164.227:28451] AH01215: #2 /home2/user/public_html/elastic/test.php(4): Elasticsearch\\ClientBuilder->build(): /usr/local/cpanel/cgi-sys/ea-php56
[Mon Oct 17 19:45:29.532222 2016] [cgi:error] [pid 25245] [client 163.158.164.227:28451] AH01215:   thrown in /home2/user/public_html/elastic/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 521: /usr/local/cpanel/cgi-sys/ea-php56



**Clientbuilder Configuration File Information**
$hosts = [
    '141.185.173.164:80',         // IP + Port
    '141.185.173.164',              // Just IP
    #'mydomain.server.com:9201', // Domain + Port
    #'mydomain2.server.com',     // Just Domain
    #'https://localhost',        // SSL to localhost
    'https://141.185.173.164:80'  // SSL to IP + Port
];
$client = ClientBuilder::create()           // Instantiate a new ClientBuilder
                    ->setHosts($hosts)      // Set the hosts
                    ->build();              // Build the client object


$client = ClientBuilder::create()   // Instantiate a new ClientBuilder
            ->setLogger($logger)        // Set your custom logger
            ->build();
$logger = ClientBuilder::defaultLogger('/home/tamiltv/public_html/elastic/error2.log');

$client = ClientBuilder::create()   // Instantiate a new ClientBuilder
            ->setLogger($logger)        // Set the logger with a default logger
            ->build();                  // Build the client object



**`Php File`**
<?php
require 'vendor/autoload.php';
#$client = Elasticsearch\ClientBuilder::create()->build();
$client = Elasticsearch\ClientBuilder::create()->setHosts('141.185.173.164')->build();

$params = array();
$params['index'] = 'm_new2';
$params['type'] = 'tags';
$params['id'] = '57c635a13f27dfe0363ef66f';

$result = $client->get($params);
?>




### System details
- Operating System - Centos 7
- PHP Version  - 5.6.26
- ES-PHP client version - 2.21
- Elasticsearch version - 2.4.1
```

**Comment by polyfractal** [comment]
The exception contains the relevant information:

```
InvalidArgumentException' with message 'Hosts parameter must be an array of strings'
```

The hosts array needs to be an array of strings, while you're just providing a single string.  Try this: 

```php
$client = Elasticsearch\ClientBuilder::create()->setHosts(['141.185.173.164'])->build();
```

Note: if your Elasticsearch is running on port 80, you'll need to include that in the host:

```php
$client = Elasticsearch\ClientBuilder::create()->setHosts(['141.185.173.164:80'])->build();
```
