### ISSUE TITLE
Unable to fail gracefully when connecting to disabled cluster

### ISSUE THREAD

**Issue by mohmad-null** [elastic/elasticsearch-php#535]
I am trying to get my code to fail gracefully if the cluster is disabled/off.
My code is this:

```
try {
	# Connects to localhost:9200 by default
	$es_conn = Elasticsearch\ClientBuilder::create()->build();

} catch (Exception $e) {
	echo "foo barred";
	exit();
}
```

But despite being within a try/catch, it seems the catch is never triggered. The exception I receive never changes:

> <br />
> <b>Fatal error</b>:  Uncaught exception 'Elasticsearch\Common\Exceptions\NoNodesAvailableException' with message 'No alive nodes found in your cluster' in c:\www\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php:51
> Stack trace:
> #0 c:\www\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(72): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool-&gt;nextConnection()
> #1 c:\www\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(90): Elasticsearch\Transport-&gt;getConnection()
> #2 c:\www\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(229): Elasticsearch\Transport-&gt;performRequest('GET', '/all/ogc/_searc...', Array, '{&quot;query&quot;:{&quot;mult...', Array)
> #3 c:\www\react\promise\src\FulfilledPromise.php(25): Elasticsearch\Connections\Connection-&gt;Elasticsearch\Connections\{closure}(Array)
> #4 c:\www\guzzlehttp\ringphp\src\Future\CompletedFutureValue.php(55): Rea in <b>c:\www\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php</b> on line <b>51</b><br />

As you can see, the entire exception is within the ES-PHP library; there's no reference to my script which is the actual trigger. I've tried googling around and there are plenty of people who get this exception accidentally (configuration issues), but I've found no indication of anyone intentionally catching things for quality-control purposes. Is this not possible?

Relatedly - I've looked through the entire set of documentation and there's nothing on exceptions except disabling them on a per-query basis. Conversely, the Python API does have a page for all exceptions - https://elasticsearch-py.readthedocs.io/en/master/exceptions.html so it's possible to know how to what you're trying to catch.

**Comment by afoucret** [comment]
You are just probably trying to catch the exception while being into a namespace.
PHP requires that you are using :
```
} catch (\Exception $e) {
```

instead of  :
```
} catch (Exception $e) {
```

A better option would be to target the right exception using :
```
} catch (\Elasticsearch\Common\Exceptions\NoNodesAvailableException $e) {
```

BR

**Comment by polyfractal** [comment]
Agreeing with @afoucret.  Closing due to inactivity.  Please feel free to reopen if you can provide more details. :)
