### ISSUE TITLE
Postman works but not the php client on bitnami-elasticsearch

### ISSUE THREAD

**Issue by deepakkakran** [elastic/elasticsearch-php#536]
when i try Postman, it works with the elasticsearch, but when i try to use the phpclient, it gives the below error.

Fatal error: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in C:\Program Files\Ampps\www\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php:51 Stack trace: #0 C:\Program Files\Ampps\www\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(72): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection() #1 C:\Program Files\Ampps\www\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(90): Elasticsearch\Transport->getConnection() #2 C:\Program Files\Ampps\www\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(227): Elasticsearch\Transport->performRequest('POST', '/articles/artic...', Array, '{"title":"dsfsd...', Array) #3 C:\Program Files\Ampps\www\elastic\vendor\react\promise\src\FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #4 C:\Program Files\Ampps\www\e in C:\Program Files\Ampps\www\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php on line 51

**Comment by zmf0507** [comment]
same problem with me i guesss...any help

**Comment by polyfractal** [comment]
My guess is that this is related to authentication somehow.  

- Does Bitnami use authentication or SSL?
- Does Bitnami use the standard 9200 ports?

**Comment by polyfractal** [comment]
Closing due to inactivity.  Please feel free to reopen if you can provide more details. :)
