### ISSUE TITLE
Fatal error: Uncaught exception 'Elasticsearch... PHP-ES-5 / ES-5.1.2

### ISSUE THREAD

**Issue by RodrigoVilanova** [elastic/elasticsearch-php#541]
hi there,

I´m getting this message from my server:
Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\NoNodesAvailableException' with message 'No alive nodes found in your cluster' in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51 Stack trace:
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(72): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(90): Elasticsearch\Transport->getConnection()
#2 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Transport->performRequest('GET', '/_cat/indices', Array, NULL, Array)
#3 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#4 /var/www/html/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Clos in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51

The weird situation is:
I have exactly same code in my local machine accessing same server and I get correct answer.
When I run same code in ES / Apache / PHP machine I got this message.
there is no firewall on server.
Any clue?

- CentOS7 
- PHP 5.6.30
- ES-PHP 5.0 
- Elasticsearch 5.1.2

**Comment by RodrigoVilanova** [comment]
Solved. Issue was httpd_can_network_connect set to false in Apache.
